# Dataset Parameters
dataset_params:
  train:
    H_path: '/scratch/work/prakritip23/diffusion_model/Benchmark_Data_COST2100/DATA_Htrainout.mat'
    codeword_dir: null

  test:
    H_path: '/scratch/work/prakritip23/diffusion_model/Benchmark_Data_COST2100/Benchmark_Data_COST2100/DATA_Htestout.mat'
    codeword_dir: null

# Diffusion Model Parameters
diffusion_params:
  num_timesteps: 100
  beta_start: 0.0001
  beta_end: 0.02
  noise_schedule: 'linear'

# Model parameters (UNet)
model_params:
  code_dim: 128
  base_ch: 4
  time_dim: 128
  stride: 2
  num_heads: 4
  num_layers: 1
  use_linear_layer: False

# Training Parameters
train_params:
  task_name: 'csi_compression'
  batch_size: 200
  batch_size_test: 1000
  num_epochs: 100
  num_samples: 1000
  num_grid_rows: 10
  lr: 0.0001
  ckpt_name: 'checkpoint_50.pth'

# Test Parameters
test_params:
  test_subset_size: 20000
  task_name: 'csi_compression_test'
  batch_size: 200
  batch_size_test: 1000
  num_epochs: 50
  num_samples: 1000
  num_grid_rows: 10
  lr: 0.0001
  ckpt_name: 'checkpoint_50.pth'

# Optimizer Parameters
optimizer_params:
  optimizer: 'adamw'
  weight_decay: 1e-5
  betas: [0.9, 0.999]

# Scheduler Parameters
scheduler_params:
  lr_scheduler: 'exponential'
  gamma: 0.9
  step_size: 10
